version: "3.9"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: "redis:alpine"
  web-static:
    build: ./images/static/.
    ports:
      - "80"
    labels:
      - "traefik.autodetect=true"
      - "traefik.http.routers.web-static.rule=PathPrefix(`/`)"
      # sticky session
      - "traefik.http.services.static.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.static.loadbalancer.sticky.cookie.name=static-cookie"
  web-dynamic:
    build: images/dynamic/.
    ports:
      - "3000"
    labels:
      - "traefik.autodetect=true"
      - "traefik.http.routers.dynamic.rule=(Host(`localhost`) && PathPrefix(`/api`))"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000